
apiVersion: apps/v1
kind: Deployment
metadata:
  name: snake-game-deployment
  labels:
    app: snake-game
spec:
  replicas: 2
  selector:
    matchLabels:
      app: snake-game
  template:
    metadata:
      name: snake-game
      labels:
        app: snake-game
    spec:
          containers:
            - name: snake-game
              image: rahulgadre/snake-game
              ports:
               - containerPort: 80
                 protocol: TCP

          
