apiVersion: v1
kind: Service
metadata:
  name: snake-service
  labels:
    app: snake-game
spec:
  selector:
      app: snake-game
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  
  
